/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Access: () => import('#controllers/access_controller'),
  Companies: () => import('#controllers/companies_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
}
