/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CompanySchema extends BaseModel {
  static $columns = [
    'address',
    'affiliationNumber',
    'createdAt',
    'id',
    'image',
    'latitude',
    'longitude',
    'name',
    'phone',
    'updatedAt',
  ] as const
  $columns = CompanySchema.$columns
  @column()
  declare address: string
  @column()
  declare affiliationNumber: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare image: string | null
  @column()
  declare latitude: string | null
  @column()
  declare longitude: string | null
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NonAdminUserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'role', 'updatedAt', 'userId'] as const
  $columns = NonAdminUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'fullName',
    'id',
    'password',
    'role',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
